version: '3.9'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8091:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - php-fpm
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tubespw
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
